# Generated by Django 5.2.5 on 2025-08-25 10:25

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('interests', models.CharField(blank=True, max_length=255, null=True)),
                ('status_message', models.CharField(blank=True, max_length=120, null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to=accounts.models.profile_pic_upload)),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to=accounts.models.cover_upload)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to=accounts.models.background_upload)),
                ('theme_choice', models.CharField(default='default', max_length=20)),
                ('theme_color', models.CharField(default='#ffffff', max_length=20)),
                ('font_choice', models.CharField(default='default', max_length=50)),
                ('music', models.FileField(blank=True, null=True, upload_to='music/')),
                ('music_autoplay', models.BooleanField(default=False)),
                ('profile_views', models.PositiveIntegerField(default=0)),
                ('profile_privacy', models.CharField(choices=[('public', 'Public'), ('friends', 'Friends Only'), ('private', 'Only Me')], default='public', max_length=10)),
                ('gallery_privacy', models.CharField(choices=[('public', 'Public'), ('friends', 'Friends Only'), ('private', 'Only Me')], default='public', max_length=10)),
                ('testimonial_privacy', models.CharField(choices=[('public', 'Public'), ('friends', 'Friends Only'), ('private', 'Only Me')], default='public', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=accounts.models.gallery_upload)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='accounts.album')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='accounts.profile')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='accounts.profile'),
        ),
        migrations.CreateModel(
            name='ProfileVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visited_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='accounts.profile')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-visited_at'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_hidden', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='accounts.profile')),
            ],
        ),
        migrations.CreateModel(
            name='TopFive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('movies', 'Movies'), ('music', 'Music'), ('games', 'Games'), ('friends', 'Friends'), ('custom', 'Custom')], default='music', max_length=20)),
                ('title', models.CharField(default='My Top 5', max_length=100)),
                ('items', models.TextField(help_text='Enter up to 5 items, one per line')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topfives', to='accounts.profile')),
            ],
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('from_user', 'to_user')},
            },
        ),
    ]
